name: 'configure-ssh-auth-sock'
description: 'Configures an ssh-agent on a given SSH_AUTH_SOCK to use a private key to connect to a given domain'
author: 'Red Hat CoP'
icon: package
color: purple
inputs:
  domain:
    description: 'Domain to configure SSH to connect to'
    required: true
  private_key:
    description: 'Private key to configure SSH to use'
    required: true
  ssh_auth_sock:
    description: 'SSH agent socket'
    default: "/tmp/ssh_agent.sock"
    required: false
  ssh_port:
    description: "SSH port to use for connecting"
    default: "22"
    required: false
  git_repo
    description: "please just work"
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.domain }}
    - ${{ inputs.private_key }}
    - ${{ inputs.ssh_auth_sock }}
    - ${{ inputs.ssh_port }}
    - ${{ inputs.git_repo}}